export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
}

export const userConstants = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",
}

export const categoryConstants = {
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
  CREATE_CATEGORY_REQUEST: "CREATE_CATEGORY_REQUEST",
  CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
  CREATE_CATEGORY_FAILURE: "CREATE_CATEGORY_FAILURE",
}

export const productConstants = {
  GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAILURE: "GET_ALL_PRODUCT_FAILURE",
  GET_PRODUCT_BY_SLUG: "GET_PRODUCT_BY_SLUG",
  GET_PRODUCT_PAGE_REQUEST: "GET_PRODUCT_PAGE_REQUEST",
  GET_PRODUCT_PAGE_SUCCESS: "GET_PRODUCT_PAGE_SUCCESS",
  GET_PRODUCT_PAGE_FAILURE: "GET_PRODUCT_PAGE_FAILURE",
  GET_PRODUCT_PAGE_BY_ID_REQUEST: "GET_PRODUCT_PAGE_BY_ID_REQUEST",
  GET_PRODUCT_PAGE_BY_ID_SUCCESS: "GET_PRODUCT_PAGE_BY_ID_SUCCESS",
  GET_PRODUCT_PAGE_BY_ID_FAILURE: "GET_PRODUCT_PAGE_BY_ID_FAILURE",
}

export const initialDataConstants = {
  GET_ALL_INITIALDATA_REQUEST: "GET_ALL_INITIALDATA_REQUEST",
  GET_ALL_INITIALDATA_SUCCESS: "GET_ALL_INITIALDATA_SUCCESS",
  GET_ALL_INITIALDATA_FAILURE: "GET_ALL_INITIALDATA_FAILURE",
}

export const cartConstants = {
  ADD_TO_CART: "ADD_TO_CART"
}